version: '3'

services:
  db:
    image: datacoding/datacodingrepohub:postgress-v1.0
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - odoo_network

  odoo:
    image: datacoding/datacodingrepohub:odoo-v1.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo_data:/var/lib/odoo
      - odoo_config:/etc/odoo
    networks:
      - odoo_network

networks:
  odoo_network:
    driver: bridge

volumes:
  pgdata:
  odoo_data:
  odoo_config: